#!/bin/bash

# Tests!
# $ sudo ./test.sh

script_dir="$(dirname "$BASH_SOURCE")"

echo "KIDDIE MODE"
echo "Go to the root directory" 
source ./wrapper.sh -k "Go to the root directory"
echo "List all the files, including hidden files, in the current directory" 
source ./wrapper.sh -k "List all the files, including hidden files, in the current directory"
echo "Go to the directory /usr/share and display the name of the directory" 
source ./wrapper.sh -k "Go to the directory /usr/share and display the name of the directory"
echo "Create a new directory named \`test_dir\` in the current directory" 
source ./wrapper.sh -k "Create a new directory named \`test_dir\` in the current directory"
echo "Delete the directory named \`test_dir\`" 
source ./wrapper.sh -k "Delete the directory named \`test_dir\`"
echo "Create a text file named \`test_file.txt\` in the current directory" 
source ./wrapper.sh -k "Create a text file named \`test_file.txt\` in the current directory"
echo "Write the text \"Hello, World!\" into \`test_file.txt\`" 
source ./wrapper.sh -k "Write the text \"Hello, World!\" into \`test_file.txt\`"
echo "Append the text \"Goodbye, World!\" to \`test_file.txt\`" 
source ./wrapper.sh -k "Append the text \"Goodbye, World!\" to \`test_file.txt\`"
echo "Read and display the contents of \`test_file.txt\`" 
source ./wrapper.sh -k "Read and display the contents of \`test_file.txt\`"
echo "Rename \`test_file.txt\` to \`renamed_file.txt\`" 
source ./wrapper.sh -k "Rename \`test_file.txt\` to \`renamed_file.txt\`"
echo "Copy \`renamed_file.txt\` to \`copied_file.txt\`" 
source ./wrapper.sh -k "Copy \`renamed_file.txt\` to \`copied_file.txt\`"
echo "Move \`copied_file.txt\` to the directory ~" 
source ./wrapper.sh -k "Move \`copied_file.txt\` to the directory ~"
echo "Delete \`renamed_file.txt\`" 
source ./wrapper.sh -k "Delete \`renamed_file.txt\`"
echo "Display the total number of files in the current directory" 
source ./wrapper.sh -k "Display the total number of files in the current directory"
echo "Display the size of a specific file setup.sh in bytes" 
source ./wrapper.sh -k "Display the size of a specific file setup.sh in bytes"
echo "Find all files in the current directory with the \`.txt\` extension" 
source ./wrapper.sh -k "Find all files in the current directory with the \`.txt\` extension"
echo "Search for the word \"Hello\" in all \`.txt\` files in the current directory" 
source ./wrapper.sh -k "Search for the word \"Hello\" in all \`.txt\` files in the current directory"
echo "Count the number of lines in \`test_file.txt\`" 
source ./wrapper.sh -k "Count the number of lines in \`test_file.txt\`"
echo "Display the most recently modified file in the current directory" 
source ./wrapper.sh -k "Display the most recently modified file in the current directory"
echo "Display the current working directory path" 
source ./wrapper.sh -k "Display the current working directory path"
echo "Create a tar archive named \`backup.tar\` containing all \`.txt\` files in the current directory" 
source ./wrapper.sh -k "Create a tar archive named \`backup.tar\` containing all \`.txt\` files in the current directory"
echo "Extract the \`backup.tar\` archive into a new directory named \`extracted_backup\`" 
source ./wrapper.sh -k "Extract the \`backup.tar\` archive into a new directory named \`extracted_backup\`"
echo "Find the file named \`bee_movie.txt\` on this computer and search for all the times the word 'bee' appears in it" 
source ./wrapper.sh -k "Find the file named \`bee_movie.txt\` on this computer and search for all the times the word 'bee' appears in it"

echo "NORMIE MODE"
echo "List all the files, including hidden files, in the current directory" 
source ./wrapper.sh "List all the files, including hidden files, in the current directory" && cd $script_dir

echo "PRO MODE"
echo "List files in the /root directory"
sudo ./wrapper.sh -p "List files in the /root directory"

echo "DONE WITH THESTS"
